#!/bin/bash
# just a sample repl
# parse space separated tokens
# no real error checking is performed on the input

source ./lib

num='([-+]?[0-9]+(\.[0-9]+)?)'

math () {
  local a b
  clean "$2"; a=$REPLY
  clean "$3"; b=$REPLY
  case $1 in
    ^) exp "$a" "$b" ;;
    +) add "$a" "$b" ;;
    -) sub "$a" "$b" ;;
    /) div "$a" "$b" ;;
    *) mul "$a" "$b" ;;
  esac
}

parse () {
  line=$1
  while :; do
    if [[ $line =~ $num" "*(\^)" "*$num(.*) ]]; then
      matches=("${BASH_REMATCH[@]}")
      math "${BASH_REMATCH[3]}" "${BASH_REMATCH[1]}" "${BASH_REMATCH[4]}"
    elif [[ $line =~ $num" "*([*/])" "*$num(.*) ]]; then
      matches=("${BASH_REMATCH[@]}")
      math "${BASH_REMATCH[3]}" "${BASH_REMATCH[1]}" "${BASH_REMATCH[4]}"
    elif [[ $line =~ $num" "*([+-])" "*$num(.*) ]]; then
      matches=("${BASH_REMATCH[@]}")
      math "${BASH_REMATCH[3]}" "${BASH_REMATCH[1]}" "${BASH_REMATCH[4]}"
    elif [[ $line =~ ^" "*$num" "*$ ]]; then
      matches=
      read REPLY <<< "$line"
      break
    elif [[ $line =~ -" "*$num(.*) ]]; then # negative num
      matches=("${BASH_REMATCH[@]}")
      math - 0 "${BASH_REMATCH[1]}"
    else break
    fi
    line="${line%%"${matches[0]}"} $REPLY ${matches[6]}"
    read -a array <<< "$line"
    line=${array[*]}
  done
  REPLY=" $REPLY "
}

while read -rep "> " line; do
  [[ $line ]] || continue
  history -s -- "$line"
  line="($line)"
  while [[ $line =~ (.*)\(([^")"]*)\)(.*) ]]; do
    REPLY=
    before=${BASH_REMATCH[1]} middle=${BASH_REMATCH[2]} after=${BASH_REMATCH[3]}
    parse "$middle"
    line=$before$REPLY$after
  done
  read line <<< "$line"
  clean "$line"
  echo "$REPLY"
done
